[default]
src = 'src'
out = 'out'
libs = ['lib']
libraries = []
memory_limit = 33554432
names = true
no_storage_caching = false
offline = false
optimizer = true
optimizer_runs = 1_000

[ci]
optimizer = false
fuzz_runs = 4069
force = true
verbosity = 4
